ALTER TABLE cards
ADD COLUMN fail_count SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN hard_count SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN good_count SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN easy_count SMALLINT NOT NULL DEFAULT 0,
DROP COLUMN revision_weight;

ALTER TABLE decks
DROP COLUMN user_id;
