CREATE TABLE cards (
  id SERIAL PRIMARY KEY,
  front TEXT NOT NULL,
  back TEXT NOT NULL,
  fail_count SMALLINT NOT NULL DEFAULT 0,
  hard_count SMALLINT NOT NULL DEFAULT 0,
  good_count SMALLINT NOT NULL DEFAULT 0,
  easy_count SMALLINT NOT NULL DEFAULT 0
)
