CREATE TABLE decks (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE cards (
  id SERIAL PRIMARY KEY,
  deck_id INT NOT NULL,
  front TEXT NOT NULL,
  back TEXT NOT NULL,
  fail_count SMALLINT NOT NULL DEFAULT 0,
  hard_count SMALLINT NOT NULL DEFAULT 0,
  good_count SMALLINT NOT NULL DEFAULT 0,
  easy_count SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_deck
    FOREIGN KEY(deck_id) 
      REFERENCES decks(id)
      ON DELETE CASCADE
);
